/*
 * Accounts Analyser
 *
 * This API is for managing bank account statements, for use with [https://github.com/Accounts-Analyser](https://github.com/Accounts-Analyser)
 *
 * API version: 1.0.0
 * Contact: colincampbell321123@hotmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Statement API!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/yokall/AccountsAnalyser/1.0.0/",
		Index,
	},

	Route{
		"AddTransaction",
		strings.ToUpper("Post"),
		"/yokall/AccountsAnalyser/1.0.0/transaction",
		AddTransaction,
	},

	Route{
		"DeleteTransaction",
		strings.ToUpper("Delete"),
		"/yokall/AccountsAnalyser/1.0.0/transaction/{transactionId}",
		DeleteTransaction,
	},

	Route{
		"GetTransactionById",
		strings.ToUpper("Get"),
		"/yokall/AccountsAnalyser/1.0.0/transaction/{transactionId}",
		GetTransactionById,
	},

	Route{
		"UpdateTransaction",
		strings.ToUpper("Put"),
		"/yokall/AccountsAnalyser/1.0.0/transaction",
		UpdateTransaction,
	},
}
